export function previewModel() {
    const phases = ["constitution", "specify", "clarify", "plan", "tasks",
        "taskstoissues", "analyze", "checklist", "implement"];
    const outputs = {
        constitution: { outputs: [".specify/memory/constitution.md"],
            view: ".specify/memory/constitution.md" },
        specify: { outputs: ["specs/<slug>/spec.md",
            "specs/<slug>/checklists/requirements.md"], view: "specs/<slug>/spec.md" },
        clarify: { outputs: ["specs/<slug>/spec.md"], view: "specs/<slug>/spec.md" },
        plan: { outputs: ["specs/<slug>/plan.md"], view: "specs/<slug>/plan.md" },
        tasks: { outputs: ["specs/<slug>/tasks.md"], view: "specs/<slug>/tasks.md" },
        taskstoissues: { outputs: [], view: null },
        analyze: { outputs: [], view: null },
        checklist: { outputs: [], view: null },
        implement: { outputs: [], view: null },
    };
    const badgeTypes = [
        ["value-match", "Value match", "Matches text anywhere in one selected output, ignoring capitalization.",
            "Value matched", "amber"],
        ["artifact-current", "Artifact current", "Shows whether a selected output is current.",
            "Artifact current", "green"],
        ["artifact-stale", "Artifact stale", "Shows when an existing output is stale relative to selected earlier outputs.",
            "Artifact stale", "amber"],
        ["markdown-file-count", "Markdown files", "Counts Markdown files beside a selected output.",
            "Files ({count})", "blue"],
        ["checklist-progress", "Checklist progress", "Count checked and total items in a current Markdown checklist.",
            "Checklist: {completed}/{total} complete", "blue"],
        ["checklist-complete", "Checklist complete", "Shows when every item in a current checklist is checked.",
            "Checklist complete", "green"],
        ["phase-run-complete", "Phase run complete", "Shows when a selected phase run completes.",
            "Phase run complete", "blue"],
    ].map(([id, title, description, defaultText, defaultColor]) =>
        ({ id, rule: id, title, description, defaultText, defaultColor, enabled: true }));
    const artifact = [{ id: "artifact", type: "artifact" }];
    const badgeRules = [
        { id: "value-match", description: "Match text anywhere in one selected output, ignoring capitalization.",
            inputs: [{ id: "artifact", type: "artifact", label: "Output to search" },
                { id: "value", type: "text", label: "Text to match" }], textPlaceholders: [] },
        { id: "checklist-progress", description: "The checklist must be current and contain at least one checkbox. The badge shows the number of checked boxes out of the total. A missing or stale checklist shows no progress badge.",
            inputs: [{ id: "artifact", type: "artifact", label: "Checklist file" },
                { id: "prerequisites", type: "ordered-artifacts", scope: "metadata",
                    before: "artifact", minItems: 1, label: "Currentness chain" },
                { id: "targetphase", type: "phase", label: "Target phase" }],
            textPlaceholders: ["completed", "total", "percent"] },
        { id: "markdown-file-count", description: "Count regular Markdown files in the selected output folder.",
            inputs: [{ id: "artifact", type: "artifact", scope: "directory" }],
            textPlaceholders: ["count"] },
        { id: "artifact-current", description: "Check whether the selected output is current.",
            inputs: artifact, textPlaceholders: [] },
        { id: "checklist-complete", description: "Check every item in a current checklist.",
            inputs: [{ id: "artifact", type: "artifact", label: "Checklist file" },
                { id: "prerequisites", type: "ordered-artifacts", scope: "metadata",
                    before: "artifact", minItems: 1, label: "Currentness chain" },
                { id: "targetphase", type: "phase", label: "Target phase" }],
            textPlaceholders: [] },
        { id: "phase-run-complete", description: "Check the selected phase's latest run.",
            inputs: [{ id: "phase", type: "phase" }], textPlaceholders: [] },
        { id: "artifact-stale", description: "Check whether an existing output is stale relative to selected earlier outputs.",
            inputs: [{ id: "artifact", type: "artifact", scope: "metadata", label: "Output to check" },
                { id: "prerequisites", type: "ordered-artifacts", scope: "metadata",
                    before: "artifact", minItems: 1, label: "Earlier outputs to check" }],
            textPlaceholders: [] },
    ];
    return { revision: "designer-preview", settingsRevision: 0, persisted: true,
        pages: [{ page: "designer-badges", title: "Badges",
            description: "Add result badges for your configured phases and outputs.",
            fixedControl: "designer.badges", fields: [] }],
        phases, outputs, pipelineOutputs: outputs, badges: [], badgeTypes, badgeRules,
        badgeInputControls: badgeRules.map((rule) => ({ rule: rule.id,
            control: "preview.badge-inputs", adapter: "preview-badge-input" })),
        values: {}, constraints: {}, controls: [], adapters: {}, templates: [] };
}
